# Generated by Django 3.2.8 on 2021-11-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211115_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='Blog hay'),
        ),
    ]
